apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.djangoapp.deploymentName }}
  labels:
    app: {{ .Values.djangoapp.name }}
spec:
  replicas: {{ .Values.djangoapp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.djangoapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.djangoapp.name }}
    spec:
      containers:
        - name: {{ .Values.djangoapp.containerName }}
          image: "{{ .Values.djangoapp.image.repository }}:{{ .Values.djangoapp.image.tag }}"
          imagePullPolicy: {{ .Values.djangoapp.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.djangoapp.image.containerPort }}
