apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.djangoapp.service.name }}
  labels:
    app: {{ .Values.djangoapp.label.app }}
spec:
  type: {{ .Values.djangoapp.service.type }}
  selector:
    app: {{ .Values.djangoapp.label.app }}
  ports:
    - port: {{ .Values.djangoapp.service.port }}
      targetPort: {{ .Values.djangoapp.container.port }}
      protocol: TCP
