apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.djangoapp.deployment.name }}
  labels:
    app: {{ .Values.djangoapp.label.app }}
spec:
  replicas: {{ .Values.djangoapp.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.djangoapp.label.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.djangoapp.label.app }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:14
          command: ["sh", "-c", "until pg_isready -h $DB_HOST -p $DB_PORT; do echo 'Waiting for PostgreSQL...'; sleep 2; done;"]
          envFrom:
          - configMapRef:
              name: postgres-config
      containers:
        - name: {{ .Values.djangoapp.container.name }}
          image: "{{ .Values.djangoapp.container.image.repository }}:{{ .Values.djangoapp.container.image.tag }}"
          imagePullPolicy: {{ .Values.djangoapp.container.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.djangoapp.container.port }}
          envFrom:
          - configMapRef:
              name: postgres-config

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.djangoapp.service.name }}
  labels:
    app: {{ .Values.djangoapp.label.app }}
spec:
  type: {{ .Values.djangoapp.service.type }}
  selector:
    app: {{ .Values.djangoapp.label.app }}
  ports:
    - port: {{ .Values.djangoapp.service.port }}
      targetPort: {{ .Values.djangoapp.container.port }}
      protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.djangoapp.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.djangoapp.service.name }}
                port:
                  number: {{ .Values.djangoapp.service.port }}