apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.djangoapp.serviceName }}
  labels:
    app: {{ .Values.djangoapp.name }}
spec:
  type: {{ .Values.djangoapp.serviceType }}
  selector:
    app: {{ .Values.djangoapp.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.djangoapp.image.containerPort }}
      protocol: TCP
