pipeline {
    agent any

    environment {
        PROJECT_DIR = "/var/lib/jenkins/workspace/test-pipeline/jenkins/elastic_beanstalk"
        DOCKERHUB_CREDENTIALS_ID = "dockerhub-credentials"
        DOCKERHUB_USERNAME = "amarkanth"
        EB_APP_NAME = "eb-test-app"
        EB_ENV_NAME = "Eb-test-app-env-3"
        S3_BUCKET = "elasticbeanstalk-ap-south-1-058264205719"
        VERSION = "build-${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                sshagent(['my-github-ssh']) {
                    sh """
                        if [ -d "jenkins" ]; then
                            rm -rf jenkins
                        fi
                        git clone git@github.com:AmarKanth/jenkins.git
                    """
                }
            }
        }

        stage('Build Docker Image And Run Tests') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh """
                        docker build -t client-test -f ./client/Dockerfile.dev ./client
                        docker run --rm -e CI=true client-test npm run test -- --coverage || true
                    """
                }
            }
        }

        stage('Build Prod Docker Images') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh """
                        docker build -t client ./client
                        docker build -t nginx ./nginx
                        docker build -t server ./server
                        docker build -t worker ./worker
                    """
                }
            }
        }

        stage('Push Prod Images to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKERHUB_CREDENTIALS_ID}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh """
                        echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
                        
                        docker tag client ${DOCKERHUB_USERNAME}/client:latest
                        docker tag nginx ${DOCKERHUB_USERNAME}/nginx:latest
                        docker tag server ${DOCKERHUB_USERNAME}/server:latest
                        docker tag worker ${DOCKERHUB_USERNAME}/worker:latest

                        docker push ${DOCKERHUB_USERNAME}/client:latest
                        docker push ${DOCKERHUB_USERNAME}/nginx:latest
                        docker push ${DOCKERHUB_USERNAME}/server:latest
                        docker push ${DOCKERHUB_USERNAME}/worker:latest
                    """
                }
            }
        }

        stage('Prepare Deployment Bundle') {
            steps {
                dir("${PROJECT_DIR}") {
                    script {
                        sh """
                            zip -r deploy.zip Dockerrun.aws.json
                            aws s3 cp deploy.zip s3://${S3_BUCKET}/deploy-${VERSION}.zip
                        """
                    }
                }
            }
        }

        stage('Create Application Version') {
            steps {
                script {
                    sh """
                        aws elasticbeanstalk create-application-version \
                            --application-name ${EB_APP_NAME} \
                            --version-label ${VERSION} \
                            --source-bundle S3Bucket=${S3_BUCKET},S3Key=deploy-${VERSION}.zip
                    """
                }
            }
        }

        stage('Deploy to Elastic Beanstalk') {
            steps {
                script {
                    sh """
                        aws elasticbeanstalk update-environment \
                            --environment-name ${EB_ENV_NAME} \
                            --version-label ${VERSION}
                    """
                }
            }
        }
    }

    post {
        always {
            script {
                sh "docker system prune -f"
            }
        }
    }
}
