djangoapp:
  label:
    app: django
    tier: backend
    environment: dev

  container:
    name: django-container
    image:
      repository: amarkanth/django-helm-test
      tag: "latest"
      pullPolicy: Always
    port: 8000
    command: ["python", "manage.py", "runserver", "-b", "0.0.0.0:8000"]

  deployment:
    name: django-deployment
    replicaCount: 3

  service:
    name: django-service
    type: ClusterIP
    port: 80

database:
  label:
    app: postgres
    tier: database
    environment: dev

  deployment:
    name: postgres-deployment
    replicaCount: 1

  service:
    name: postgres-service
    type: ClusterIP
    port: 5432

  container:
    name: postgres-container
    port: 5432
    image:
      repository: postgres
      tag: "14"
      pullPolicy: IfNotPresent
    env:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme
    volume:
      name: db-storage
      mountPath: /var/lib/postgresql/data
      hostPath: /mnt/data/db
      type: DirectoryOrCreate

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
